export const API_ENDPOINTS = {
  HEALTH: "/health",
  AUTH_TOKEN: "/auth/token",
  USER_PERMISSIONS: "/users/permissions",
  USERS: "/users",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  EMPLOYEES: "/employees",
  CUSTOMERS: "/customers",
  BRANCHES: "/branches",
  PICKUPS: "/pickups",
  PICKUP_ROUTES: "/pickups/route",
  CONTAINERS: "/containers",
  DELIVERIES: "/deliveries",
  BARCODES: "/barcodes",
  VEHICLES: "/vehicles",
  INVOICES: "/invoices",
  INVOICE_DESCRIPTIONS: "/invoice-descriptions",
} as const;
