export const API_ENDPOINTS = {
  HEALTH: "/health",
  AUTH_TOKEN: "/auth/token",
  USER_PERMISSIONS: "/users/permissions",
  USERS: "/users",
  CURRENT_USER: "/users/current",
  CURRENT_USER_PREFERENCES: "/users/me/preferences",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  EMPLOYEES: "/employees",
  CUSTOMERS: "/customers",
  BRANCHES: "/branches",
  PICKUPS: "/pickups",
  PICKUP_ROUTES: "/pickups/route",
  CONTAINERS: "/containers",
  DELIVERIES: "/deliveries",
  BARCODES: "/barcodes",
  VEHICLES: "/vehicles",
  ROUTES: "/routes",
  /** Scheduled pickup/delivery route (unified endpoint; `routeType` in payload). */
  VEHICLE_ROUTES: "/vehicle-routes",
  /** @deprecated Use VEHICLE_ROUTES. */
  PICKUP_ROUTE_SCHEDULES: "/vehicle-routes",
  /** @deprecated Use VEHICLE_ROUTES. */
  DELIVERY_ROUTE_SCHEDULES: "/vehicle-routes",
  INVOICES: "/invoices",
  INVOICE_ITEM_BARCODE_ROUTE: "/invoices/item/barcode/route",
  INVOICE_DETAIL_LABELS: "/invoice/detail/labels",
  INVOICE_DETAIL_BARCODE: "/invoice/detail/barcode",
  INVOICE_DETAIL_BARCODE_STATUSES: "/invoice/detail/barcode/statuses",
  INVOICE_DESCRIPTIONS: "/invoice-descriptions",
  ACCOUNTING_INCOME_STATEMENTS: "/income-statements",
  ACCOUNTING_INCOME_STATEMENT: "/income-statements",
  ACCOUNTING_JOURNALS: "/journals",
  ACCOUNTING_JOURNAL: "/journals",
  CHART_ACCOUNTS: "/chart-accounts",
  ACCOUNTING_PAYMENT_METHODS: "/accounting/paymentmethods",
  REPORTS_INCOME: "/reports/income",
  REPORTS_INVOICES: "/reports/invoices",
  REPORTS_JOURNALS: "/reports/journals",
  REPORTS_LABELS: "/reports/labels",
  REPORTS_PICKUPS: "/reports/pickups",
  /** Public PDF download; append `/{token}`. */
  REPORTS_PUBLIC: "/public/reports",
  FILTER_PRESETS: "/filter-presets",
  MEMO_PADS: "/memo-pads",
} as const;
