import type { ApiTableField } from "@/lib/table/api-table-fields";

/** Directory coverage for api-docs.json definitions["journal.Journal"]. */
export const DAILY_INCOME_JOURNAL_API_TABLE_FIELDS = [
  { field: "accounts" },
  { field: "checkNumber" },
  { field: "createdAt", format: "date" },
  { field: "createdBy" },
  { field: "currency" },
  { field: "customer" },
  { field: "date", format: "date" },
  { field: "description" },
  { field: "duplicatePaymentOverride" },
  { field: "employee" },
  { field: "employeeGroup" },
  { field: "external_reference_number" },
  { field: "id" },
  { field: "idempotencyKey" },
  { field: "incomeStatement" },
  { field: "invoice" },
  { field: "loan" },
  { field: "loanTransaction" },
  { field: "paymentMethod" },
  { field: "rate" },
  { field: "refNumber", columnId: "reference" },
  { field: "route" },
  { field: "sourceBranchId" },
  { field: "sourceBranchName" },
  { field: "sourceCreatedBy" },
  { field: "sourceCustomerId" },
  { field: "sourceCustomerName" },
  { field: "sourceId" },
  { field: "sourceIncomeStatementId" },
  { field: "sourceInvoiceId" },
  { field: "sourceInvoiceNumber" },
  { field: "sourceJournalIds" },
  { field: "sourcePaymentMethodId" },
  { field: "sourcePaymentType" },
  { field: "sourceSupervisorId" },
  { field: "sourceSupervisorName" },
  { field: "sourceSystem" },
  { field: "sourceTransactionNumber" },
  { field: "sourceTransactionTypeId" },
  { field: "transactionAmount", columnId: "amount" },
  { field: "transactionBalance" },
  { field: "transactionID" },
  { field: "transactionType", columnId: "type" },
  { field: "updatedAt", format: "date" },
  { field: "updatedBy" },
  { field: "vehicleRoute" },
] as const satisfies readonly ApiTableField[];
