import { DEFAULT_CREATED_BY } from "@/lib/audit/constants";
import { deriveInventoryStatus, type InventoryItem } from "./types";

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "inv-001",
    sku: "PKG-BOX-M",
    name: "Medium shipping boxes (18x12x10)",
    category: "packaging",
    location: "ny_warehouse",
    quantity: 420,
    reserved: 48,
    reorderLevel: 100,
    unit: "boxes",
    status: "in_stock",
    notes: "Primary outbound carton for domestic routes.",
    createdAt: "2026-06-04T14:22:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T14:22:00Z",
  },
  {
    id: "inv-002",
    sku: "LBL-4X6-ROLL",
    name: "Thermal label rolls 4x6",
    category: "labels",
    location: "ny_warehouse",
    quantity: 18,
    reserved: 6,
    reorderLevel: 20,
    unit: "rolls",
    status: "low_stock",
    createdAt: "2026-06-04T11:05:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T11:05:00Z",
  },
  {
    id: "inv-003",
    sku: "PKG-TAPE-CLR",
    name: "Clear packing tape",
    category: "supplies",
    location: "rd_warehouse",
    quantity: 96,
    reserved: 12,
    reorderLevel: 30,
    unit: "rolls",
    status: "in_stock",
    createdAt: "2026-06-03T18:40:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-03T18:40:00Z",
  },
  {
    id: "inv-004",
    sku: "EQP-SCAN-HH",
    name: "Handheld barcode scanners",
    category: "equipment",
    location: "ny_warehouse",
    quantity: 0,
    reserved: 0,
    reorderLevel: 2,
    unit: "units",
    status: "out_of_stock",
    notes: "Reorder approved — vendor lead time 5 days.",
    createdAt: "2026-06-02T09:15:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-02T09:15:00Z",
  },
  {
    id: "inv-005",
    sku: "PKG-BUBBLE-L",
    name: "Large bubble wrap rolls",
    category: "packaging",
    location: "in_transit",
    quantity: 60,
    reserved: 60,
    reorderLevel: 15,
    unit: "rolls",
    status: "reserved",
    createdAt: "2026-06-04T08:00:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T08:00:00Z",
  },
  {
    id: "inv-006",
    sku: "SUP-PALLET-WRAP",
    name: "Stretch pallet wrap",
    category: "supplies",
    location: "dock",
    quantity: 34,
    reserved: 0,
    reorderLevel: 12,
    unit: "rolls",
    status: "review",
    notes: "Count mismatch after last unload — recount scheduled.",
    createdAt: "2026-06-04T16:30:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T16:30:00Z",
  },
  {
    id: "inv-007",
    sku: "LBL-ZEB-203",
    name: "Zebra 203 DPI label stock",
    category: "labels",
    location: "rd_warehouse",
    quantity: 240,
    reserved: 20,
    reorderLevel: 50,
    unit: "sheets",
    status: "in_stock",
    createdAt: "2026-06-01T13:20:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-01T13:20:00Z",
  },
  {
    id: "inv-008",
    sku: "PKG-BOX-L",
    name: "Large shipping boxes (24x18x12)",
    category: "packaging",
    location: "ny_warehouse",
    quantity: 8,
    reserved: 2,
    reorderLevel: 25,
    unit: "boxes",
    status: "low_stock",
    createdAt: "2026-06-04T10:45:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T10:45:00Z",
  },
  {
    id: "inv-009",
    sku: "SUP-MARK-BLK",
    name: "Permanent markers (black)",
    category: "supplies",
    location: "rd_warehouse",
    quantity: 150,
    reserved: 0,
    reorderLevel: 40,
    unit: "units",
    status: "in_stock",
    createdAt: "2026-05-30T17:00:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-05-30T17:00:00Z",
  },
  {
    id: "inv-010",
    sku: "EQP-SCALE-50",
    name: "50 lb digital floor scale",
    category: "equipment",
    location: "dock",
    quantity: 3,
    reserved: 1,
    reorderLevel: 1,
    unit: "units",
    status: "in_stock",
    createdAt: "2026-05-28T12:00:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-05-28T12:00:00Z",
  },
  {
    id: "inv-011",
    sku: "PKG-ENVELOPE",
    name: "Padded mailers 10x13",
    category: "packaging",
    location: "ny_warehouse",
    quantity: 0,
    reserved: 0,
    reorderLevel: 80,
    unit: "units",
    status: "out_of_stock",
    createdAt: "2026-06-03T07:30:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-03T07:30:00Z",
  },
  {
    id: "inv-012",
    sku: "LBL-CUSTOM-A",
    name: "Custom client label template A",
    category: "labels",
    location: "in_transit",
    quantity: 500,
    reserved: 120,
    reorderLevel: 100,
    unit: "labels",
    status: "in_stock",
    createdAt: "2026-06-04T15:10:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T15:10:00Z",
  },
];

export function normalizeInventoryItem(
  values: Omit<InventoryItem, "id" | "status" | "createdAt" | "createdBy" | "updatedAt"> & {
    id?: string;
    status?: InventoryItem["status"];
    createdAt?: string;
    createdBy?: string;
    updatedAt?: string;
  }
): InventoryItem {
  const status = values.status ?? deriveInventoryStatus(values.quantity, values.reserved, values.reorderLevel);
  const updatedAt = values.updatedAt ?? new Date().toISOString();
  return {
    ...values,
    id: values.id ?? `inv-${Date.now()}`,
    status,
    createdAt: values.createdAt ?? updatedAt,
    createdBy: values.createdBy ?? DEFAULT_CREATED_BY,
    updatedAt,
  };
}

export function cloneInventoryItems(): InventoryItem[] {
  return MOCK_INVENTORY_ITEMS.map((item) => ({ ...item }));
}
