import {
  BarChart3,
  Barcode,
  Boxes,
  ClipboardList,
  Container,
  FileText,
  Home,
  KeyRound,
  Package,
  PackageCheck,
  Route,
  ScanBarcode,
  Settings,
  ShieldCheck,
  Tag,
  Truck,
  UserCog,
  UserRound,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";

export const navigation = [
  { title: "Workspace", items: [
    { label: "Dashboard", href: "/", icon: Home },
    { label: "Customers", href: "/customers", icon: Users },
    { label: "Orders", href: "/orders", icon: Package },
    { label: "Invoices", href: "/invoices", icon: FileText },
    { label: "Labels", href: "/labels", icon: Barcode },
    { label: "Label Updater", href: "/label-updater", icon: ScanBarcode },
    { label: "Inventory", href: "/inventory", icon: Boxes },
    { label: "Items", href: "/items", icon: Tag },
    { label: "Containers", href: "/containers", icon: Container },
    { label: "Routes", href: "/routes", icon: Route },
    { label: "Route Assignments", href: "/route-assignments", icon: ClipboardList },
    { label: "Trucks", href: "/trucks", icon: Truck },
    { label: "Deliveries", href: "/deliveries", icon: PackageCheck },
  ]},
  { title: "Insights", items: [
    { label: "Accounting", href: "/accounting", icon: Wallet },
    { label: "Reports", href: "/reports", icon: FileText },
    { label: "Analytics", href: "/analytics", icon: BarChart3 },
  ]},
  { title: "Admin", items: [
    { label: "Users", href: "/users", icon: UserCog },
    { label: "Roles", href: "/roles", icon: KeyRound },
    { label: "Employees", href: "/employees", icon: UsersRound },
    { label: "Employee Groups", href: "/employee-groups", icon: UserRound },
    { label: "Security", href: "/security", icon: ShieldCheck },
    { label: "Configuration", href: "/settings", icon: Settings },
  ]},
];
