import type { TableFilterFieldDefinition } from "@/lib/table/filter-builder";

const TEXT_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;
const DATE_OPERATORS = ["eq", "neq", "gte", "lte"] as const;
const NUMERIC_OPERATORS = ["eq", "neq", "gte", "lte", "gt", "lt"] as const;
const PHONE_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;

export const INVOICE_TABLE_FILTER_FIELDS: TableFilterFieldDefinition[] = [
  {
    field: "number",
    label: "Invoice number",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter invoice number…",
  },
  {
    field: "numberRange",
    label: "Invoice number range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "488800 to 488900",
  },
  {
    field: "date",
    label: "Date",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "dateRange",
    label: "Date range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
  {
    field: "paidRegion",
    label: "Paid at",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "NY", label: "USA" },
      { value: "RD", label: "DR" },
    ],
  },
  {
    field: "paidStatus",
    label: "Status",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "OPEN", label: "Open" },
      { value: "CLOSED", label: "Closed" },
    ],
  },
  {
    field: "cost",
    label: "Invoice total",
    operators: [...NUMERIC_OPERATORS],
    valueType: "text",
    placeholder: "Enter amount…",
  },
  {
    field: "discount",
    label: "Discount",
    operators: [...NUMERIC_OPERATORS],
    valueType: "text",
    placeholder: "Enter amount…",
  },
  {
    field: "payment",
    label: "Paid",
    operators: [...NUMERIC_OPERATORS],
    valueType: "text",
    placeholder: "Enter amount…",
  },
  {
    field: "balance",
    label: "Balance",
    operators: [...NUMERIC_OPERATORS],
    valueType: "text",
    placeholder: "Enter amount…",
  },
  {
    field: "container.name",
    label: "Container",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter container…",
  },
  {
    field: "sender.name",
    label: "Sender",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter sender name…",
  },
  {
    field: "sender.id",
    label: "Sender ID",
    operators: ["eq", "neq", "in", "notIn"],
    valueType: "text",
    placeholder: "Enter sender ID…",
  },
  {
    field: "sender.phone",
    label: "Sender phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["sender.phones.number", "sender.phone1"],
  },
  {
    field: "sender.address",
    label: "Sender address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address, city, state, or zip…",
    queryFields: [
      "sender.address.address1",
      "sender.address.address2",
      "sender.address.city",
      "sender.address.state",
      "sender.address.zipcode",
    ],
  },
  {
    field: "receiver.name",
    label: "Receiver",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter receiver name…",
  },
  {
    field: "receiver.id",
    label: "Receiver ID",
    operators: ["eq", "neq", "in", "notIn"],
    valueType: "text",
    placeholder: "Enter receiver ID…",
  },
  {
    field: "receiver.phone",
    label: "Receiver phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["receiver.phones.number", "receiver.phone1"],
  },
  {
    field: "receiver.address",
    label: "Receiver address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address, city, state, or zip…",
    queryFields: [
      "receiver.address.address1",
      "receiver.address.address2",
      "receiver.address.city",
      "receiver.address.state",
      "receiver.address.zipcode",
    ],
  },
  {
    field: "createdBy.name",
    label: "Created by",
    operators: ["eq", "neq", "contains", "startsWith"],
    valueType: "select",
    optionsSource: "users",
  },
  {
    field: "route._id",
    label: "Route",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "routes",
  },
  {
    field: "employee.id",
    label: "Employee ID",
    operators: ["eq", "neq"],
    valueType: "text",
    placeholder: "Enter employee ID…",
  },
  {
    field: "employee.name",
    label: "Employee name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter employee name…",
  },
  {
    field: "isArchive",
    label: "Archived",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  {
    field: "isVoid",
    label: "Void",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  {
    field: "createdAt",
    label: "Created at",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "createdAtRange",
    label: "Created at range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
  {
    field: "updatedAt",
    label: "Updated at",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "updatedAtRange",
    label: "Updated at range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
];
