import type { Invoice } from "./types";

export const MOCK_INVOICES: Invoice[] = [
  {
    invoiceId: "inv-001",
    invoiceNumber: "INV-2026-0001",
    date: "2026-02-05",
    containerId: "cnt-001",
    paymentLocation: "usa",
    sender: {
      id: "party-is-001",
      clientId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      name: "North Harbor Supply Co.",
      documentId: "NH-88421",
      email: "dispatch@northharbor.example",
      phones: [{ id: "iph-001", number: "+1 (718) 555-0142", label: "Dispatch" }],
      addresses: [
        {
          id: "ipa-001",
          streetAddress: "245 Atlantic Ave",
          apt: "Suite 400",
          city: "Brooklyn",
          state: "NY",
          provinceCountry: "USA",
          zipCode: "11201",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-001",
    },
    receiver: {
      id: "party-ir-001",
      clientId: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      name: "María Rodríguez",
      documentId: "001-1234567-8",
      phones: [{ id: "iph-002", number: "+1 (809) 555-3321", label: "Mobile" }],
      addresses: [
        {
          id: "ipa-002",
          streetAddress: "Calle El Conde 118",
          city: "Santo Domingo",
          provinceCountry: "Distrito Nacional, RD",
          zipCode: "10210",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-002",
    },
    lineItems: [
      {
        id: "ili-001",
        itemId: "itm-001",
        itemName: "Standard shipping box — medium (18×14×12 in)",
        quantity: 10,
        labelCount: 10,
        unitPrice: 4.5,
        lineTotal: 45,
      },
      {
        id: "ili-002",
        itemId: "itm-003",
        itemName: "Packing tape roll — 2 in × 110 yd",
        quantity: 5,
        labelCount: 5,
        unitPrice: 3.25,
        lineTotal: 16.25,
      },
    ],
    discount: 5,
    amountPaid: 40,
    payments: [
      {
        id: "pay-001",
        invoiceId: "inv-001",
        description: "Partial payment at Brooklyn office",
        amount: 25,
        paymentMethod: "check",
        referenceNumber: "CHK-8842",
        createdAt: "2026-02-04T14:30:00Z",
        createdBy: "Hector Mejia",
      },
      {
        id: "pay-002",
        invoiceId: "inv-001",
        description: "Cash payment on follow-up visit",
        amount: 15,
        paymentMethod: "cash",
        referenceNumber: "",
        createdAt: "2026-02-05T08:00:00Z",
        createdBy: "Hector Mejia",
      },
    ],
    comments: [
      {
        id: "ic-001",
        description: "Tried reaching out by phone — no answer. Left voicemail.",
        createdAt: "2026-02-04T11:15:00Z",
        createdBy: "Hector Mejia",
      },
      {
        id: "ic-002",
        description: "Customer called back. They only want delivery in the morning before 11 AM.",
        createdAt: "2026-02-05T09:40:00Z",
        createdBy: "Hector Mejia",
      },
    ],
    activity: [
      {
        id: "ia-001",
        invoiceId: "inv-001",
        action: "created",
        message: "Invoice INV-2026-0001 created.",
        timestamp: "2026-02-04T10:00:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-002",
        invoiceId: "inv-001",
        action: "discount_change",
        message: "Discount of $5.00 applied.",
        timestamp: "2026-02-04T10:00:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-003",
        invoiceId: "inv-001",
        action: "payment",
        message: "Payment of $25.00 recorded. Total paid: $0.00 → $25.00.",
        timestamp: "2026-02-04T14:30:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-004",
        invoiceId: "inv-001",
        action: "comment_added",
        message: "Comment added: Tried reaching out by phone — no answer. Left voicemail.",
        timestamp: "2026-02-04T11:15:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-005",
        invoiceId: "inv-001",
        action: "payment",
        message: "Payment of $15.00 recorded. Total paid: $25.00 → $40.00.",
        timestamp: "2026-02-05T08:00:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-006",
        invoiceId: "inv-001",
        action: "comment_added",
        message:
          "Comment added: Customer called back. They only want delivery in the morning before 11 AM.",
        timestamp: "2026-02-05T09:40:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-007",
        invoiceId: "inv-001",
        action: "updated",
        message: "Invoice edited: line items (2 items / $61.25 → 2 items / $61.25).",
        timestamp: "2026-06-04T14:22:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
    ],
    createdAt: "2026-02-04T10:00:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-04T14:22:00Z",
  },
  {
    invoiceId: "inv-002",
    invoiceNumber: "INV-2026-0002",
    date: "2026-03-01",
    containerId: "cnt-002",
    paymentLocation: "dr",
    sender: {
      id: "party-is-002",
      clientId: "c3d4e5f6-a7b8-9012-cdef-123456789012",
      name: "Blue Coast Foods",
      phones: [{ id: "iph-003", number: "+1 (305) 555-7788" }],
      addresses: [
        {
          id: "ipa-003",
          streetAddress: "8800 NW 36th St",
          city: "Doral",
          state: "FL",
          provinceCountry: "USA",
          zipCode: "33166",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-003",
    },
    receiver: {
      id: "party-ir-002",
      clientId: "d4e5f6a7-b8c9-0123-def0-234567890123",
      name: "Carlos Méndez",
      phones: [{ id: "iph-004", number: "+1 (809) 555-4410" }],
      addresses: [
        {
          id: "ipa-004",
          streetAddress: "Av. Winston Churchill 1099",
          city: "Santo Domingo",
          provinceCountry: "Distrito Nacional, RD",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-004",
    },
    lineItems: [
      {
        id: "ili-003",
        itemId: "itm-002",
        itemName: "55-gallon plastic barrel — food grade",
        quantity: 4,
        labelCount: 4,
        unitPrice: 38,
        lineTotal: 152,
      },
      {
        id: "ili-004",
        itemId: "itm-005",
        itemName: "Door-to-door delivery service fee",
        quantity: 1,
        labelCount: 0,
        unitPrice: 25,
        lineTotal: 25,
      },
    ],
    discount: 0,
    amountPaid: 177,
    payments: [
      {
        id: "pay-101",
        invoiceId: "inv-002",
        description: "Full invoice payment before container departure",
        amount: 177,
        paymentMethod: "wire_transfer",
        referenceNumber: "WT-20260301-778",
        createdAt: "2026-03-01T10:00:00Z",
        createdBy: "Hector Mejia",
      },
    ],
    comments: [
      {
        id: "ic-003",
        description: "Receiver prefers WhatsApp contact only — do not call after 6 PM.",
        createdAt: "2026-03-01T08:20:00Z",
        createdBy: "Hector Mejia",
      },
    ],
    activity: [
      {
        id: "ia-101",
        invoiceId: "inv-002",
        action: "created",
        message: "Invoice INV-2026-0002 created.",
        timestamp: "2026-02-28T15:30:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-102",
        invoiceId: "inv-002",
        action: "payment",
        message: "Payment of $177.00 recorded. Total paid: $0.00 → $177.00.",
        timestamp: "2026-03-01T10:00:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
      {
        id: "ia-103",
        invoiceId: "inv-002",
        action: "comment_added",
        message: "Comment added: Receiver prefers WhatsApp contact only — do not call after 6 PM.",
        timestamp: "2026-03-01T08:20:00Z",
        performedBy: "Hector Mejia",
        success: true,
      },
    ],
    createdAt: "2026-02-28T15:30:00Z",
    createdBy: "Hector Mejia",
    updatedAt: "2026-06-03T11:05:00Z",
  },
  {
    invoiceId: "inv-003",
    invoiceNumber: "INV-2026-0003",
    date: "2026-04-10",
    containerId: "cnt-003",
    paymentLocation: "usa",
    sender: {
      id: "party-is-003",
      clientId: "e5f6a7b8-c9d0-1234-ef01-345678901234",
      name: "Metro Logistics LLC",
      phones: [{ id: "iph-005", number: "+1 (212) 555-2200" }],
      addresses: [
        {
          id: "ipa-005",
          streetAddress: "350 Fifth Ave",
          city: "New York",
          state: "NY",
          provinceCountry: "USA",
          zipCode: "10118",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-005",
    },
    receiver: {
      id: "party-ir-003",
      clientId: "f6a7b8c9-d0e1-2345-f012-456789012345",
      name: "Ana Lucía Pérez",
      phones: [{ id: "iph-006", number: "+1 (849) 555-9022" }],
      addresses: [
        {
          id: "ipa-006",
          streetAddress: "Calle Duarte 45",
          city: "Santiago",
          provinceCountry: "Santiago, RD",
          zipCode: "51000",
          isPrimary: false,
        },
      ],
      orderAddressId: "ipa-006",
    },
    lineItems: [
      {
        id: "ili-005",
        itemId: "itm-004",
        itemName: "Custom wooden crate — large",
        quantity: 2,
        labelCount: 2,
        unitPrice: 85,
        lineTotal: 170,
      },
      {
        id: "ili-006",
        itemId: "itm-006",
        itemName: "Fragile handling surcharge",
        quantity: 2,
        labelCount: 0,
        unitPrice: 12.5,
        lineTotal: 25,
      },
    ],
    discount: 15,
    amountPaid: 50,
    payments: [
      {
        id: "pay-201",
        invoiceId: "inv-003",
        description: "Deposit toward custom crate shipment",
        amount: 50,
        paymentMethod: "zelle",
        referenceNumber: "ZEL-449021",
        createdAt: "2026-04-10T16:00:00Z",
        createdBy: "Admin User",
      },
    ],
    comments: [],
    activity: [
      {
        id: "ia-201",
        invoiceId: "inv-003",
        action: "created",
        message: "Invoice INV-2026-0003 created.",
        timestamp: "2026-04-08T09:15:00Z",
        performedBy: "Admin User",
        success: true,
      },
      {
        id: "ia-202",
        invoiceId: "inv-003",
        action: "discount_change",
        message: "Discount of $15.00 applied.",
        timestamp: "2026-04-08T09:15:00Z",
        performedBy: "Admin User",
        success: true,
      },
      {
        id: "ia-203",
        invoiceId: "inv-003",
        action: "payment",
        message: "Payment of $50.00 recorded. Total paid: $0.00 → $50.00.",
        timestamp: "2026-04-10T16:00:00Z",
        performedBy: "Admin User",
        success: true,
      },
    ],
    createdAt: "2026-04-08T09:15:00Z",
    createdBy: "Admin User",
    updatedAt: "2026-06-02T18:40:00Z",
  },
];

export function cloneInvoices(): Invoice[] {
  return MOCK_INVOICES.map((invoice) => ({
    ...invoice,
    sender: {
      ...invoice.sender,
      phones: invoice.sender.phones.map((phone) => ({ ...phone })),
      addresses: invoice.sender.addresses.map((address) => ({ ...address })),
    },
    receiver: {
      ...invoice.receiver,
      phones: invoice.receiver.phones.map((phone) => ({ ...phone })),
      addresses: invoice.receiver.addresses.map((address) => ({ ...address })),
    },
    lineItems: invoice.lineItems.map((item) => ({ ...item })),
    comments: invoice.comments.map((comment) => ({ ...comment })),
    activity: invoice.activity.map((entry) => ({ ...entry })),
    payments: invoice.payments.map((payment) => ({ ...payment })),
  }));
}

export function getInvoiceById(invoiceId: string): Invoice | undefined {
  return MOCK_INVOICES.find((invoice) => invoice.invoiceId === invoiceId);
}
