import type { ApiTableField } from "@/lib/table/api-table-fields";

/** Directory coverage for api-docs.json definitions["invoice.Invoice"]. */
export const INVOICE_API_TABLE_FIELDS = [
  { field: "balance" },
  { field: "branch", defaultVisible: false },
  { field: "container" },
  { field: "cost", columnId: "total" },
  { field: "createdAt", format: "date", defaultVisible: false },
  { field: "createdBy", defaultVisible: false },
  { field: "date", format: "date" },
  { field: "discount" },
  { field: "employee", columnId: "pickupAssignment" },
  { field: "id", defaultVisible: false },
  { field: "invoiceDetails", defaultVisible: false },
  { field: "isArchive", defaultVisible: false },
  { field: "isVoid", defaultVisible: false },
  { field: "legacySyncedAt", format: "date", defaultVisible: false },
  { field: "number", columnId: "invoiceNumber" },
  { field: "officeBranch", defaultVisible: false },
  { field: "paidRegion", columnId: "paymentLocation", defaultVisible: false },
  { field: "paidStatus" },
  { field: "payment", columnId: "amountPaid" },
  { field: "pickup", defaultVisible: false },
  { field: "pickupEmployee", defaultVisible: false },
  { field: "pickupSource", defaultVisible: false },
  { field: "receivedBy", columnId: "pickupAssignment", defaultVisible: false },
  { field: "receiver", columnId: "receiver.name" },
  { field: "registration", defaultVisible: false },
  { field: "route", columnId: "pickupAssignment", defaultVisible: false },
  { field: "sender", columnId: "sender.name" },
  { field: "surcharge", defaultVisible: false },
  { field: "updatedAt", format: "date", defaultVisible: false },
  { field: "updatedBy", defaultVisible: false },
] as const satisfies readonly ApiTableField[];
