import type { ApiTableField } from "@/lib/table/api-table-fields";

/** Directory coverage for api-docs.json definitions["invoice.Invoice"]. */
export const INVOICE_API_TABLE_FIELDS = [
  { field: "balance" },
  { field: "branch" },
  { field: "container" },
  { field: "cost", columnId: "total" },
  { field: "createdAt", format: "date" },
  { field: "createdBy" },
  { field: "date", format: "date" },
  { field: "discount" },
  { field: "employee", columnId: "pickupAssignment" },
  { field: "id" },
  { field: "invoiceDetails" },
  { field: "isArchive" },
  { field: "isVoid" },
  { field: "legacySyncedAt", format: "date" },
  { field: "number", columnId: "invoiceNumber" },
  { field: "officeBranch" },
  { field: "paidRegion", columnId: "paymentLocation" },
  { field: "paidStatus" },
  { field: "payment", columnId: "amountPaid" },
  { field: "pickup" },
  { field: "pickupEmployee" },
  { field: "pickupSource" },
  { field: "receivedBy", columnId: "pickupAssignment" },
  { field: "receiver", columnId: "receiver.name" },
  { field: "registration" },
  { field: "route", columnId: "pickupAssignment" },
  { field: "sender", columnId: "sender.name" },
  { field: "surcharge" },
  { field: "updatedAt", format: "date" },
  { field: "updatedBy" },
] as const satisfies readonly ApiTableField[];
