import type { TableFilterFieldDefinition } from "@/lib/table/filter-builder";

const TEXT_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;
const DATE_OPERATORS = ["eq", "neq", "gte", "lte"] as const;
const PHONE_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;

const SENDER_ADDRESS_QUERY_FIELDS = [
  "sender.address.address1",
  "sender.address.address2",
  "sender.address.city",
  "sender.address.state",
  "sender.address.zipcode",
];

const RECEIVER_ADDRESS_QUERY_FIELDS = [
  "receivers.address.address1",
  "receivers.address.address2",
  "receivers.address.city",
  "receivers.address.state",
  "receivers.address.zipcode",
];

export const ORDER_TABLE_FILTER_FIELDS: TableFilterFieldDefinition[] = [
  {
    field: "sender.name",
    label: "Name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter name…",
  },
  {
    field: "sender.phone",
    label: "Phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["sender.phone"],
  },
  {
    field: "sender.address",
    label: "Address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address, city, state, or zip…",
    queryFields: SENDER_ADDRESS_QUERY_FIELDS,
  },
  {
    field: "sender.address.city",
    label: "City",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter city…",
  },
  {
    field: "sender.address.state",
    label: "State",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter state…",
  },
  {
    field: "sender.address.zipcode",
    label: "Zip",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter zip code…",
  },
  {
    field: "sender.zipRange",
    label: "Zip range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "10001-10282 or 10001 to 10282",
  },
  {
    field: "purpose",
    label: "Purpose",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter purpose…",
  },
  {
    field: "comments",
    label: "Comments",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter comment text…",
  },
  {
    field: "route.id",
    label: "Appointment route",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "pickupRoutes",
  },
  {
    field: "branch.id",
    label: "Branch",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "branches",
  },
  {
    field: "branch.code",
    label: "Branch code",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "branchCodes",
  },
  {
    field: "branch.name",
    label: "Branch name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter branch name…",
  },
  {
    field: "receivers.name",
    label: "Receiver name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter receiver name…",
  },
  {
    field: "receivers.phone",
    label: "Receiver phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["receivers.phone"],
  },
  {
    field: "receivers.address",
    label: "Receiver address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address, city, state, or zip…",
    queryFields: RECEIVER_ADDRESS_QUERY_FIELDS,
  },
  {
    field: "receivers.address.city",
    label: "Receiver city",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter city…",
  },
  {
    field: "receivers.address.state",
    label: "Receiver state",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter state…",
  },
  {
    field: "receivers.address.zipcode",
    label: "Receiver zip",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter zip code…",
  },
  {
    field: "createdBy.name",
    label: "Created by",
    operators: ["eq", "neq", "contains", "startsWith"],
    valueType: "select",
    optionsSource: "users",
  },
  {
    field: "completed",
    label: "Completed status",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "false", label: "Pending" },
      { value: "true", label: "Completed" },
    ],
  },
  {
    field: "date",
    label: "Appointment date",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "dateRange",
    label: "Appointment date range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
  {
    field: "createdAt",
    label: "Date created",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "createdAtRange",
    label: "Date created range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
];
