import type { TableFilterFieldDefinition } from "@/lib/table/filter-builder";

const TEXT_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;
const DATE_OPERATORS = ["eq", "neq", "gte", "lte"] as const;
const PHONE_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;

export const ORDER_TABLE_FILTER_FIELDS: TableFilterFieldDefinition[] = [
  {
    field: "sender.name",
    label: "Sender name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter sender name…",
  },
  {
    field: "sender.phone",
    label: "Sender phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["sender.phones.number", "sender.phone1"],
  },
  {
    field: "sender.address.address1",
    label: "Sender address 1",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address line 1…",
  },
  {
    field: "sender.address.address2",
    label: "Sender address 2",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address line 2…",
  },
  {
    field: "sender.address.city",
    label: "Sender city",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter city…",
  },
  {
    field: "sender.address.state",
    label: "Sender state",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter state…",
  },
  {
    field: "sender.address.zipcode",
    label: "Sender zip",
    operators: [...TEXT_OPERATORS, "gte", "lte"],
    valueType: "text",
    placeholder: "Enter zip code…",
  },
  {
    field: "sender.zipRange",
    label: "Sender zip range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "10001-10282 or 10001 to 10282",
  },
  {
    field: "purpose",
    label: "Purpose",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter purpose…",
  },
  {
    field: "receiver.name",
    label: "Receiver name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter receiver name…",
  },
  {
    field: "receiver.phone",
    label: "Receiver phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["receiver.phones.number", "receiver.phone1"],
  },
  {
    field: "receiver.address.address1",
    label: "Receiver address 1",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address line 1…",
  },
  {
    field: "receiver.address.address2",
    label: "Receiver address 2",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter address line 2…",
  },
  {
    field: "receiver.address.city",
    label: "Receiver city",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter city…",
  },
  {
    field: "receiver.address.state",
    label: "Receiver state",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter state…",
  },
  {
    field: "receiver.address.zipcode",
    label: "Receiver zip",
    operators: [...TEXT_OPERATORS, "gte", "lte"],
    valueType: "text",
    placeholder: "Enter zip code…",
  },
  {
    field: "user.name",
    label: "Created by",
    operators: ["eq", "neq", "contains", "startsWith"],
    valueType: "select",
    optionsSource: "users",
  },
  {
    field: "completed",
    label: "Completed status",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "false", label: "Pending" },
      { value: "true", label: "Completed" },
    ],
  },
  {
    field: "date",
    label: "Order date",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "dateRange",
    label: "Order date range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
  {
    field: "createdAt",
    label: "Date created",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "createdAtRange",
    label: "Date created range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
];
