import type { TableFilterFieldDefinition } from "@/lib/table/filter-builder";

const TEXT_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;
const DATE_OPERATORS = ["eq", "neq", "gte", "lte"] as const;
const PHONE_OPERATORS = ["startsWith", "contains", "eq", "neq"] as const;

export const ORDER_TABLE_FILTER_FIELDS: TableFilterFieldDefinition[] = [
  {
    field: "sender.name",
    label: "Sender name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter sender name…",
  },
  {
    field: "sender.phone",
    label: "Sender phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["sender.phone"],
  },
  {
    field: "sender.address",
    label: "Sender address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter sender address…",
  },
  {
    field: "sender.zipRange",
    label: "Sender zip range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "10001-10282 or 10001 to 10282",
  },
  {
    field: "purpose",
    label: "Purpose",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter purpose…",
  },
  {
    field: "comments",
    label: "Comments",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter comment text…",
  },
  {
    field: "route.id",
    label: "Pickup route",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "pickupRoutes",
  },
  {
    field: "branch.id",
    label: "Branch",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "branches",
  },
  {
    field: "branch.code",
    label: "Branch code",
    operators: ["eq", "neq"],
    valueType: "select",
    optionsSource: "branchCodes",
  },
  {
    field: "branch.name",
    label: "Branch name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter branch name…",
  },
  {
    field: "receivers.name",
    label: "Receiver name",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter receiver name…",
  },
  {
    field: "receivers.phone",
    label: "Receiver phone",
    operators: [...PHONE_OPERATORS],
    valueType: "text",
    placeholder: "Enter phone…",
    queryFields: ["receivers.phone"],
  },
  {
    field: "receivers.address",
    label: "Receiver address",
    operators: [...TEXT_OPERATORS],
    valueType: "text",
    placeholder: "Enter receiver address…",
  },
  {
    field: "createdBy.name",
    label: "Created by",
    operators: ["eq", "neq", "contains", "startsWith"],
    valueType: "select",
    optionsSource: "users",
  },
  {
    field: "completed",
    label: "Completed status",
    operators: ["eq", "neq"],
    valueType: "select",
    options: [
      { value: "false", label: "Pending" },
      { value: "true", label: "Completed" },
    ],
  },
  {
    field: "date",
    label: "Order date",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "dateRange",
    label: "Order date range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
  {
    field: "createdAt",
    label: "Date created",
    operators: [...DATE_OPERATORS],
    valueType: "text",
    placeholder: "YYYY-MM-DD",
  },
  {
    field: "createdAtRange",
    label: "Date created range",
    operators: ["eq"],
    valueType: "range",
    placeholder: "2026-01-01 to 2026-06-30",
  },
];
